stages:
- build

build:
  stage: build
  image: maven:3.3.9-jdk-8
  script: "mvn clean package"
  artifacts:
    name: "UltimateRepairing"
    paths:
    - "/builds/Songoda/UltimateRepairing/target/*.jar"
    - "/builds/Songoda/UltimateRepairing/Read_this_before_your_first_use.txt"
