name: UltimateRepairing
description: UltimateRepairing
main: com.songoda.ultimaterepairing.UltimateRepairing
depend: [Arconix]
softdepend: [Vault]
version: 1
author: Songoda
api-version: 1.13
commands:
  ultimaterepairing:
    description: View information on this plugin.
    default: true
    aliases: [ur]
    usage: /ur
  rpanvil:
    description: View information on this plugin.
    default: true
    usage: /rpanvil