name: UltimateRepairing
description: UltimateRepairing
main: com.songoda.ultimaterepairing.UltimateRepairing
softdepend: [Arconix, Vault]
version: 1.0.1
author: Songoda
api-version: 1.13
commands:
  ultimaterepairing:
    description: View information on this plugin.
    default: true
    aliases: [ur]
    usage: /ur
  uranvil:
    description: View information on this plugin.
    default: true
    usage: /uranvil